"""auto migration

Revision ID: 1a5f5d194607
Revises: 0005_archive_visit_no
Create Date: 2026-08-21 19:05:26.609676
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a5f5d194607'
down_revision: str | None = '0005_archive_visit_no'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_medical_archives_user_active_visit'), table_name='medical_archives')
    op.drop_column('medical_archives', 'active_visit_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_archives', sa.Column('active_visit_no', mysql.CHAR(collation='utf8mb4_unicode_ci', length=64), sa.Computed('(if((`deleted_at` is null),`visit_no`,NULL))', persisted=True), nullable=True))
    op.create_index(op.f('uq_medical_archives_user_active_visit'), 'medical_archives', ['user_id', 'active_visit_no'], unique=True)
    # ### end Alembic commands ###
