"""更新表结构

Revision ID: 880b6b63d119
Revises: 0004_qa_multi_turn
Create Date: 2026-08-02 21:16:32.429736
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '880b6b63d119'
down_revision: str | None = '0004_qa_multi_turn'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
